version: "3.9"
services:
  mqtt_broker:
    container_name: huebot_mqtt
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /usr/local/bin/mosquitto/conf.d:/mosquitto/config/conf.d
      - /usr/local/bin/mosquitto/passwd:/etc/mosquitto/passwd
      - /usr/local/bin/mosquitto/data:/mosquitto/data
      - /usr/local/bin/mosquitto/log:/mosquitto/log
    ports:
      - 18831:1883
    networks:
      - huebot-proxy-net

networks:
  huebot-proxy-net:
    external:
      name: hubNetwork